# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_start', models.DateField()),
                ('train_end', models.DateField()),
                ('test_start', models.DateField()),
                ('test_end', models.DateField()),
                ('model_type', models.CharField(max_length=40)),
                ('model_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Strats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date_published')),
                ('train_return', models.FloatField()),
                ('test_return', models.FloatField()),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtests.Cohort')),
            ],
        ),
    ]
