# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Strats',
            new_name='Strat',
        ),
    ]
